#!/usr/bin/env python3
"""Writes src/App/ChatKeeper.vcxproj from packages.config and the source list.

packages.config projects don't import NuGet build files automatically, so the
imports for every Windows App SDK 1.8 component package are generated here.
Re-run after changing packages.config or adding source files.
"""
import glob
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
APP = os.path.join(ROOT, "src", "App")
PKG = r"$(MSBuildThisFileDirectory)..\..\packages"

# (id, props path inside the package or None, targets path or None)
LAYOUT = {
    "Microsoft.Windows.SDK.BuildTools.MSIX": ("build/Microsoft.Windows.SDK.BuildTools.MSIX.props", "build/Microsoft.Windows.SDK.BuildTools.MSIX.targets"),
    "Microsoft.Windows.SDK.BuildTools": ("build/Microsoft.Windows.SDK.BuildTools.props", "build/Microsoft.Windows.SDK.BuildTools.targets"),
    "Microsoft.WindowsAppSDK.Base": ("build/native/Microsoft.WindowsAppSDK.Base.props", "build/native/Microsoft.WindowsAppSDK.Base.targets"),
    "Microsoft.WindowsAppSDK.Foundation": ("build/native/Microsoft.WindowsAppSDK.Foundation.props", "build/native/Microsoft.WindowsAppSDK.Foundation.targets"),
    "Microsoft.WindowsAppSDK.InteractiveExperiences": ("build/native/Microsoft.WindowsAppSDK.InteractiveExperiences.props", "build/native/Microsoft.WindowsAppSDK.InteractiveExperiences.targets"),
    "Microsoft.WindowsAppSDK.WinUI": ("build/native/Microsoft.WindowsAppSDK.WinUI.props", "build/native/Microsoft.WindowsAppSDK.WinUI.targets"),
    "Microsoft.WindowsAppSDK.DWrite": ("build/Microsoft.WindowsAppSDK.DWrite.props", "build/Microsoft.WindowsAppSDK.DWrite.targets"),
    "Microsoft.WindowsAppSDK.Widgets": ("build/native/Microsoft.WindowsAppSDK.Widgets.props", "build/native/Microsoft.WindowsAppSDK.Widgets.targets"),
    "Microsoft.WindowsAppSDK.AI": ("build/native/Microsoft.WindowsAppSDK.AI.props", "build/native/Microsoft.WindowsAppSDK.AI.targets"),
    "Microsoft.WindowsAppSDK.ML": ("build/native/Microsoft.WindowsAppSDK.ML.props", "build/native/Microsoft.WindowsAppSDK.ML.targets"),
    "Microsoft.WindowsAppSDK.Runtime": ("build/native/Microsoft.WindowsAppSDK.Runtime.props", "build/native/Microsoft.WindowsAppSDK.Runtime.targets"),
    "Microsoft.WindowsAppSDK": ("build/native/Microsoft.WindowsAppSDK.props", "build/native/Microsoft.WindowsAppSDK.targets"),
    "Microsoft.Windows.CppWinRT": ("build/native/Microsoft.Windows.CppWinRT.props", "build/native/Microsoft.Windows.CppWinRT.targets"),
    "Microsoft.Web.WebView2": (None, "build/native/Microsoft.Web.WebView2.targets"),
    "Microsoft.Windows.ImplementationLibrary": (None, "build/native/Microsoft.Windows.ImplementationLibrary.targets"),
}
ORDER = list(LAYOUT.keys())


def packages():
    text = open(os.path.join(APP, "packages.config"), encoding="utf-8").read()
    found = dict(re.findall(r'<package id="([^"]+)" version="([^"]+)"', text))
    return [(i, found[i]) for i in ORDER if i in found]


def path(pid, ver, rel):
    return PKG + "\\" + pid + "." + ver + "\\" + rel.replace("/", "\\")


def main():
    pk = packages()
    props = "\n".join(
        f'  <Import Project="{path(i, v, LAYOUT[i][0])}" Condition="Exists(\'{path(i, v, LAYOUT[i][0])}\')" />'
        for i, v in pk if LAYOUT[i][0])
    targets = "\n".join(
        f'    <Import Project="{path(i, v, LAYOUT[i][1])}" Condition="Exists(\'{path(i, v, LAYOUT[i][1])}\')" />'
        for i, v in pk if LAYOUT[i][1])
    checks = "\n".join(
        f'    <Error Condition="!Exists(\'{path(i, v, rel)}\')" Text="$([System.String]::Format(\'$(ErrorText)\', \'{path(i, v, rel)}\'))" />'
        for i, v in pk for rel in LAYOUT[i] if rel)

    core = sorted(glob.glob(os.path.join(ROOT, "src", "Core", "**", "*.cpp"), recursive=True))
    core_h = sorted(glob.glob(os.path.join(ROOT, "src", "Core", "**", "*.h"), recursive=True))
    rel = lambda p: os.path.relpath(p, APP).replace("/", "\\")
    core_cl = "\n".join(f'    <ClCompile Include="{rel(p)}">\n      <PrecompiledHeader>NotUsing</PrecompiledHeader>\n    </ClCompile>' for p in core)
    core_inc = "\n".join(f'    <ClInclude Include="{rel(p)}" />' for p in core_h)
    window_parts = sorted(os.path.basename(p) for p in glob.glob(os.path.join(APP, "MainWindow.*.cpp")) if not p.endswith("MainWindow.xaml.cpp"))
    parts = "\n".join(f'    <ClCompile Include="{p}">\n      <DependentUpon>MainWindow.xaml</DependentUpon>\n    </ClCompile>' for p in window_parts)

    proj = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make_vcxproj.py. Edit there. -->
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
{props}
  <PropertyGroup Label="Globals">
    <CppWinRTOptimized>true</CppWinRTOptimized>
    <CppWinRTRootNamespaceAutoMerge>true</CppWinRTRootNamespaceAutoMerge>
    <MinimalCoreWin>true</MinimalCoreWin>
    <ProjectGuid>{{5ACFD96F-6AB1-4E7E-9FEE-A022B553EAAF}}</ProjectGuid>
    <ProjectName>ChatKeeper</ProjectName>
    <RootNamespace>ChatKeeper</RootNamespace>
    <DefaultLanguage>en-US</DefaultLanguage>
    <MinimumVisualStudioVersion>16.0</MinimumVisualStudioVersion>
    <AppContainerApplication>false</AppContainerApplication>
    <AppxPackage>false</AppxPackage>
    <WindowsTargetPlatformVersion Condition=" '$(WindowsTargetPlatformVersion)' == '' ">10.0</WindowsTargetPlatformVersion>
    <WindowsTargetPlatformMinVersion>10.0.17763.0</WindowsTargetPlatformMinVersion>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
  </PropertyGroup>
  <PropertyGroup Label="Vcpkg">
    <VcpkgEnableManifest>true</VcpkgEnableManifest>
    <VcpkgManifestRoot>$(MSBuildThisFileDirectory)..\\..\\</VcpkgManifestRoot>
    <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static-md</VcpkgTriplet>
    <VcpkgTriplet Condition="'$(Platform)'=='ARM64'">arm64-windows-static-md</VcpkgTriplet>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.Default.props" />
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|ARM64">
      <Configuration>Debug</Configuration>
      <Platform>ARM64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|ARM64">
      <Configuration>Release</Configuration>
      <Platform>ARM64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <PlatformToolset>$(DefaultPlatformToolset)</PlatformToolset>
    <CharacterSet>Unicode</CharacterSet>
    <DesktopCompatible>true</DesktopCompatible>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'" Label="Configuration">
    <UseDebugLibraries>true</UseDebugLibraries>
    <LinkIncremental>true</LinkIncremental>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'" Label="Configuration">
    <UseDebugLibraries>false</UseDebugLibraries>
    <WholeProgramOptimization>true</WholeProgramOptimization>
    <LinkIncremental>false</LinkIncremental>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
  </ImportGroup>
  <ImportGroup Label="PropertySheets">
    <Import Project="$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <ItemDefinitionGroup>
    <ClCompile>
      <PrecompiledHeader>Use</PrecompiledHeader>
      <PrecompiledHeaderFile>pch.h</PrecompiledHeaderFile>
      <PrecompiledHeaderOutputFile>$(IntDir)pch.pch</PrecompiledHeaderOutputFile>
      <WarningLevel>Level4</WarningLevel>
      <AdditionalOptions>%(AdditionalOptions) /bigobj /utf-8</AdditionalOptions>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <AdditionalIncludeDirectories>$(ProjectDir)..;$(ProjectDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>NOMINMAX;_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <DisableSpecificWarnings>4100;4189;4505;%(DisableSpecificWarnings)</DisableSpecificWarnings>
    </ClCompile>
    <Link>
      <SubSystem>Windows</SubSystem>
      <AdditionalDependencies>PortableDeviceGuids.lib;propsys.lib;shlwapi.lib;shell32.lib;ole32.lib;oleaut32.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Debug'">
    <ClCompile>
      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Release'">
    <ClCompile>
      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
    <Link>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <Manifest Include="app.manifest" />
  </ItemGroup>
  <ItemGroup>
    <ClInclude Include="pch.h" />
    <ClInclude Include="AppInfo.h" />
    <ClInclude Include="App.xaml.h">
      <DependentUpon>App.xaml</DependentUpon>
    </ClInclude>
    <ClInclude Include="MainWindow.xaml.h">
      <DependentUpon>MainWindow.xaml</DependentUpon>
    </ClInclude>
{core_inc}
  </ItemGroup>
  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" />
    <Page Include="MainWindow.xaml" />
  </ItemGroup>
  <ItemGroup>
    <ClCompile Include="pch.cpp">
      <PrecompiledHeader>Create</PrecompiledHeader>
    </ClCompile>
    <ClCompile Include="AppInfo.cpp" />
    <ClCompile Include="App.xaml.cpp">
      <DependentUpon>App.xaml</DependentUpon>
    </ClCompile>
    <ClCompile Include="MainWindow.xaml.cpp">
      <DependentUpon>MainWindow.xaml</DependentUpon>
    </ClCompile>
{parts}
    <ClCompile Include="$(GeneratedFilesDir)module.g.cpp" />
{core_cl}
  </ItemGroup>
  <ItemGroup>
    <Midl Include="MainWindow.idl">
      <SubType>Code</SubType>
      <DependentUpon>MainWindow.xaml</DependentUpon>
    </Midl>
  </ItemGroup>
  <ItemGroup>
    <PRIResource Include="Strings\\en-US\\Resources.resw" />
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\\AppIcon.png">
      <DeploymentContent>true</DeploymentContent>
    </Content>
    <Content Include="Assets\\AppIcon.ico">
      <DeploymentContent>true</DeploymentContent>
    </Content>
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
{targets}
  </ImportGroup>
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Run "nuget restore ChatKeeper.sln". The missing file is {{0}}.</ErrorText>
    </PropertyGroup>
{checks}
  </Target>
  <!-- Files the app needs next to the exe: guide images, the viewer, the bundled exporter. -->
  <Target Name="CopyAppPayload" AfterTargets="Build">
    <ItemGroup>
      <GuideImages Include="$(MSBuildThisFileDirectory)..\\..\\Assets\\Guide\\*.png" />
      <AppAssets Include="$(MSBuildThisFileDirectory)Assets\\*.*" />
      <ViewerFiles Include="$(MSBuildThisFileDirectory)..\\..\\viewer\\index.html" />
      <ExporterFiles Include="$(MSBuildThisFileDirectory)..\\..\\exporter\\**\\*" Exclude="$(MSBuildThisFileDirectory)..\\..\\exporter\\README.md" />
      <NoticeFiles Include="$(MSBuildThisFileDirectory)..\\..\\THIRD_PARTY_NOTICES.txt" />
    </ItemGroup>
    <Copy SourceFiles="@(GuideImages)" DestinationFolder="$(OutDir)Assets\\Guide" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(AppAssets)" DestinationFolder="$(OutDir)Assets" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(ViewerFiles)" DestinationFolder="$(OutDir)viewer" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(ExporterFiles)" DestinationFiles="@(ExporterFiles->'$(OutDir)exporter\\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(NoticeFiles)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
'''
    with open(os.path.join(APP, "ChatKeeper.vcxproj"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write(proj)


if __name__ == "__main__":
    main()
